---
name: Dropbox backup
version: "0.6.0"
slug: dropbox-backup
description: "Upload your Home Assistant backups to Dropbox"
url: https://github.com/ianpleasance/dropbox-backup
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

stdin: true
hassio_api: true
hassio_role: manager

map:
  - backup
  - share

# Fields available in configuration tab with default values.
options:
  app_key: null
  app_secret: null
  refresh_token: null

schema:
  app_key: str
  app_secret: str
  refresh_token: str
  output: str?
  keep_last: int(0,)?
  preserve_filename: bool?

# Download location of the package.
#image: "ghcr.io/ianpleasance/dropbox-backup/{arch}"
